package com.technology.module.supportbase.dao.po;

// default package

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectContract generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name = "projectcontract", catalog = "technology", uniqueConstraints = {})
public class ProjectContract implements java.io.Serializable
{

    // Fields

    private Integer id;
    private Integer serviceid;
    private Integer projectid;
    private String  versionnum;
    private String  name;
    private String  year;
    private Date    signtime;
    private Float   money;
    private Float   citymoney;
    private Integer progessid;
    private String  templetpath;
    private String  wordpath;
    private String  pdfpath;

    // Constructors

    /** default constructor */
    public ProjectContract() {}

    /** minimal constructor */
    public ProjectContract(Integer id) {
	this.id = id;
    }

    /** full constructor */
    public ProjectContract(Integer id, Integer serviceid, Integer projectid, String versionnum, String name, String year, Date signtime, Float money, Float citymoney, Integer progessid, String templetpath, String wordpath, String pdfpath) {
	this.id = id;
	this.serviceid = serviceid;
	this.projectid = projectid;
	this.versionnum = versionnum;
	this.name = name;
	this.year = year;
	this.signtime = signtime;
	this.money = money;
	this.citymoney = citymoney;
	this.progessid = progessid;
	this.templetpath = templetpath;
	this.wordpath = wordpath;
	this.pdfpath = pdfpath;
    }

    // Property accessors
    @Id
    @Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
    public Integer getId()
    {
	return this.id;
    }

    public void setId(Integer id)
    {
	this.id = id;
    }

    @Column(name = "serviceid", unique = false, nullable = true, insertable = true, updatable = true)
    public Integer getServiceid()
    {
	return this.serviceid;
    }

    public void setServiceid(Integer serviceid)
    {
	this.serviceid = serviceid;
    }

    @Column(name = "projectid", unique = false, nullable = true, insertable = true, updatable = true)
    public Integer getProjectid()
    {
	return this.projectid;
    }

    public void setProjectid(Integer projectid)
    {
	this.projectid = projectid;
    }

    @Column(name = "versionnum", unique = false, nullable = true, insertable = true, updatable = true, length = 50)
    public String getVersionnum()
    {
	return this.versionnum;
    }

    public void setVersionnum(String versionnum)
    {
	this.versionnum = versionnum;
    }

    @Column(name = "name", unique = false, nullable = true, insertable = true, updatable = true)
    public String getName()
    {
	return this.name;
    }

    public void setName(String name)
    {
	this.name = name;
    }

    @Column(name = "year", unique = false, nullable = true, insertable = true, updatable = true, length = 10)
    public String getYear()
    {
	return this.year;
    }

    public void setYear(String year)
    {
	this.year = year;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "signtime", unique = false, nullable = true, insertable = true, updatable = true, length = 19)
    public Date getSigntime()
    {
	return this.signtime;
    }

    public void setSigntime(Date signtime)
    {
	this.signtime = signtime;
    }

    @Column(name = "money", unique = false, nullable = true, insertable = true, updatable = true, precision = 12, scale = 0)
    public Float getMoney()
    {
	return this.money;
    }

    public void setMoney(Float money)
    {
	this.money = money;
    }

    @Column(name = "citymoney", unique = false, nullable = true, insertable = true, updatable = true, precision = 12, scale = 0)
    public Float getCitymoney()
    {
	return this.citymoney;
    }

    public void setCitymoney(Float citymoney)
    {
	this.citymoney = citymoney;
    }

    @Column(name = "progessid", unique = false, nullable = true, insertable = true, updatable = true)
    public Integer getProgessid()
    {
	return this.progessid;
    }

    public void setProgessid(Integer progessid)
    {
	this.progessid = progessid;
    }

    @Column(name = "templetpath", unique = false, nullable = true, insertable = true, updatable = true)
    public String getTempletpath()
    {
	return this.templetpath;
    }

    public void setTempletpath(String templetpath)
    {
	this.templetpath = templetpath;
    }

    @Column(name = "wordpath", unique = false, nullable = true, insertable = true, updatable = true)
    public String getWordpath()
    {
	return this.wordpath;
    }

    public void setWordpath(String wordpath)
    {
	this.wordpath = wordpath;
    }

    @Column(name = "pdfpath", unique = false, nullable = true, insertable = true, updatable = true)
    public String getPdfpath()
    {
	return this.pdfpath;
    }

    public void setPdfpath(String pdfpath)
    {
	this.pdfpath = pdfpath;
    }

}