package com.technology.module.supportbase.dao.po;
// default package

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * ProjectExecute generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name="projectexecute"
    ,catalog="technology"
, uniqueConstraints = {  }
)

public class ProjectExecute  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer serviceid;
     private Integer projectid;
     private String year;
     private String code;
     private Date signtime;
     private Integer workid;
     private String error;
     private Integer progessid;
     private String templetpath;
     private String wordpath;
     private String pdfpath;
     private Float output;
     private Float gain;
     private Float tax;
     private Float erics;
     private Float coals;
     private Float waters;
     private Integer jobs;
     private Integer doctors;
     private Integer masters;
     private Integer mediums;
     private Integer highs;
     private Integer invents;
     private Integer authorizes;
     private Integer stands;
     private Integer papers;
     private Integer books;
     private Integer awards;
     private Integer copyrights;
     private Integer products;
     private Integer equips;
     private Integer techs;
     private Integer grounds;
     private Integer materials;
     private Integer types;
     private String othernote;


    // Constructors

    /** default constructor */
    public ProjectExecute() {
    }

	/** minimal constructor */
    public ProjectExecute(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public ProjectExecute(Integer id, Integer serviceid, Integer projectid, String year, String code, Date signtime, Integer workid, String error, Integer progessid, String templetpath, String wordpath, String pdfpath, Float output, Float gain, Float tax, Float erics, Float coals, Float waters, Integer jobs, Integer doctors, Integer masters, Integer mediums, Integer highs, Integer invents, Integer authorizes, Integer stands, Integer papers, Integer books, Integer awards, Integer copyrights, Integer products, Integer equips, Integer techs, Integer grounds, Integer materials, Integer types, String othernote) {
        this.id = id;
        this.serviceid = serviceid;
        this.projectid = projectid;
        this.year = year;
        this.code = code;
        this.signtime = signtime;
        this.workid = workid;
        this.error = error;
        this.progessid = progessid;
        this.templetpath = templetpath;
        this.wordpath = wordpath;
        this.pdfpath = pdfpath;
        this.output = output;
        this.gain = gain;
        this.tax = tax;
        this.erics = erics;
        this.coals = coals;
        this.waters = waters;
        this.jobs = jobs;
        this.doctors = doctors;
        this.masters = masters;
        this.mediums = mediums;
        this.highs = highs;
        this.invents = invents;
        this.authorizes = authorizes;
        this.stands = stands;
        this.papers = papers;
        this.books = books;
        this.awards = awards;
        this.copyrights = copyrights;
        this.products = products;
        this.equips = equips;
        this.techs = techs;
        this.grounds = grounds;
        this.materials = materials;
        this.types = types;
        this.othernote = othernote;
    }

   
    // Property accessors
    @Id
    
    @Column(name="id", unique=true, nullable=false, insertable=true, updatable=true)

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="serviceid", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getServiceid() {
        return this.serviceid;
    }
    
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }
    
    @Column(name="projectid", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getProjectid() {
        return this.projectid;
    }
    
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }
    
    @Column(name="year", unique=false, nullable=true, insertable=true, updatable=true, length=10)

    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    
    @Column(name="code", unique=false, nullable=true, insertable=true, updatable=true, length=100)

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
@Temporal(TemporalType.DATE)
    @Column(name="signtime", unique=false, nullable=true, insertable=true, updatable=true, length=19)

    public Date getSigntime() {
        return this.signtime;
    }
    
    public void setSigntime(Date signtime) {
        this.signtime = signtime;
    }
    
    @Column(name="workid", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getWorkid() {
        return this.workid;
    }
    
    public void setWorkid(Integer workid) {
        this.workid = workid;
    }
    
    @Column(name="error", unique=false, nullable=true, insertable=true, updatable=true, length=50)

    public String getError() {
        return this.error;
    }
    
    public void setError(String error) {
        this.error = error;
    }
    
    @Column(name="progessid", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getProgessid() {
        return this.progessid;
    }
    
    public void setProgessid(Integer progessid) {
        this.progessid = progessid;
    }
    
    @Column(name="templetpath", unique=false, nullable=true, insertable=true, updatable=true)

    public String getTempletpath() {
        return this.templetpath;
    }
    
    public void setTempletpath(String templetpath) {
        this.templetpath = templetpath;
    }
    
    @Column(name="wordpath", unique=false, nullable=true, insertable=true, updatable=true)

    public String getWordpath() {
        return this.wordpath;
    }
    
    public void setWordpath(String wordpath) {
        this.wordpath = wordpath;
    }
    
    @Column(name="pdfpath", unique=false, nullable=true, insertable=true, updatable=true)

    public String getPdfpath() {
        return this.pdfpath;
    }
    
    public void setPdfpath(String pdfpath) {
        this.pdfpath = pdfpath;
    }
    
    @Column(name="output", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

    public Float getOutput() {
        return this.output;
    }
    
    public void setOutput(Float output) {
        this.output = output;
    }
    
    @Column(name="gain", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

    public Float getGain() {
        return this.gain;
    }
    
    public void setGain(Float gain) {
        this.gain = gain;
    }
    
    @Column(name="tax", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

    public Float getTax() {
        return this.tax;
    }
    
    public void setTax(Float tax) {
        this.tax = tax;
    }
    
    @Column(name="erics", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

    public Float getErics() {
        return this.erics;
    }
    
    public void setErics(Float erics) {
        this.erics = erics;
    }
    
    @Column(name="coals", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

    public Float getCoals() {
        return this.coals;
    }
    
    public void setCoals(Float coals) {
        this.coals = coals;
    }
    
    @Column(name="waters", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

    public Float getWaters() {
        return this.waters;
    }
    
    public void setWaters(Float waters) {
        this.waters = waters;
    }
    
    @Column(name="jobs", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Integer jobs) {
        this.jobs = jobs;
    }
    
    @Column(name="doctors", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Integer doctors) {
        this.doctors = doctors;
    }
    
    @Column(name="masters", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getMasters() {
        return this.masters;
    }
    
    public void setMasters(Integer masters) {
        this.masters = masters;
    }
    
    @Column(name="mediums", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getMediums() {
        return this.mediums;
    }
    
    public void setMediums(Integer mediums) {
        this.mediums = mediums;
    }
    
    @Column(name="highs", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getHighs() {
        return this.highs;
    }
    
    public void setHighs(Integer highs) {
        this.highs = highs;
    }
    
    @Column(name="invents", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getInvents() {
        return this.invents;
    }
    
    public void setInvents(Integer invents) {
        this.invents = invents;
    }
    
    @Column(name="authorizes", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getAuthorizes() {
        return this.authorizes;
    }
    
    public void setAuthorizes(Integer authorizes) {
        this.authorizes = authorizes;
    }
    
    @Column(name="stands", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getStands() {
        return this.stands;
    }
    
    public void setStands(Integer stands) {
        this.stands = stands;
    }
    
    @Column(name="papers", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getPapers() {
        return this.papers;
    }
    
    public void setPapers(Integer papers) {
        this.papers = papers;
    }
    
    @Column(name="books", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getBooks() {
        return this.books;
    }
    
    public void setBooks(Integer books) {
        this.books = books;
    }
    
    @Column(name="awards", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getAwards() {
        return this.awards;
    }
    
    public void setAwards(Integer awards) {
        this.awards = awards;
    }
    
    @Column(name="copyrights", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getCopyrights() {
        return this.copyrights;
    }
    
    public void setCopyrights(Integer copyrights) {
        this.copyrights = copyrights;
    }
    
    @Column(name="products", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getProducts() {
        return this.products;
    }
    
    public void setProducts(Integer products) {
        this.products = products;
    }
    
    @Column(name="equips", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getEquips() {
        return this.equips;
    }
    
    public void setEquips(Integer equips) {
        this.equips = equips;
    }
    
    @Column(name="techs", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getTechs() {
        return this.techs;
    }
    
    public void setTechs(Integer techs) {
        this.techs = techs;
    }
    
    @Column(name="grounds", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getGrounds() {
        return this.grounds;
    }
    
    public void setGrounds(Integer grounds) {
        this.grounds = grounds;
    }
    
    @Column(name="materials", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getMaterials() {
        return this.materials;
    }
    
    public void setMaterials(Integer materials) {
        this.materials = materials;
    }
    
    @Column(name="types", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getTypes() {
        return this.types;
    }
    
    public void setTypes(Integer types) {
        this.types = types;
    }
    
    @Column(name="othernote", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getOthernote() {
        return this.othernote;
    }
    
    public void setOthernote(String othernote) {
        this.othernote = othernote;
    }
   








}