package com.technology.module.supportbase.dao.po;
// default package

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Suppoortbase generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name="supportbase"
    ,catalog="technology"
, uniqueConstraints = {  }
)

public class Suppoortbase  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer serviceid;
     private Integer type;
     private Integer kind;
     private Integer rank;
     private Integer secret;
     private Integer activity;
     private Integer invoate;
     private Integer region;
     private Integer techregion;
     private String year;
     private String name;
     private String versionnum;
     private String acceptnum;
     private String projectnum;
     private String filenum;
     private Integer seq;
     private Integer progessid;
     private Integer isover;
     private Integer isbuild;
     private Integer leadid;
     private Date reporttime;
     private Date starttime;
     private Date endtime;
     private Integer source;
     private Integer creative;
     private Integer advance;
     private Integer period;
     private Integer alinvest;
     private Integer preinvest;
     private Integer alutility;
     private Integer preutility;
     private Integer alstyle;
     private Integer prestyle;
     private Integer outinvest;
     private Integer newarts;
     private Integer newproduct;
     private Integer newequip;
     private Integer soft;
     private Integer paper;
     private Integer standard;
     private Integer other1;
     private Integer other2;
     private String advantage;
     private String harvest;
     private Integer ispdf;
     private String goal;
     private String base;
     private String purpose;
     private String content;
     private String stagegoal;
     private String techgoal;
     private String bengoal;
     private String workgoal;
     private String preview;
     private String environment;
     private String othernote;
     private String fundnote;
     private String templetpath;
     private String wordpath;
     private String pdfpath;
     private String reportpath;


    // Constructors

    /** default constructor */
    public Suppoortbase() {
    }

	/** minimal constructor */
    public Suppoortbase(Integer id) {
        this.id = id;
    }
    
    /** full constructor */
    public Suppoortbase(Integer id, Integer serviceid, Integer type, Integer kind, Integer rank, Integer secret, Integer activity, Integer invoate, Integer region, Integer techregion, String year, String name, String versionnum, String acceptnum, String projectnum, String filenum, Integer seq, Integer progessid, Integer isover, Integer isbuild, Integer leadid, Date reporttime, Date starttime, Date endtime, Integer source, Integer creative, Integer advance, Integer period, Integer alinvest, Integer preinvest, Integer alutility, Integer preutility, Integer alstyle, Integer prestyle, Integer outinvest, Integer newarts, Integer newproduct, Integer newequip, Integer soft, Integer paper, Integer standard, Integer other1, Integer other2, String advantage, String harvest, Integer ispdf, String goal, String base, String purpose, String content, String stagegoal, String techgoal, String bengoal, String workgoal, String preview, String environment, String othernote, String fundnote, String templetpath, String wordpath, String pdfpath, String reportpath) {
        this.id = id;
        this.serviceid = serviceid;
        this.type = type;
        this.kind = kind;
        this.rank = rank;
        this.secret = secret;
        this.activity = activity;
        this.invoate = invoate;
        this.region = region;
        this.techregion = techregion;
        this.year = year;
        this.name = name;
        this.versionnum = versionnum;
        this.acceptnum = acceptnum;
        this.projectnum = projectnum;
        this.filenum = filenum;
        this.seq = seq;
        this.progessid = progessid;
        this.isover = isover;
        this.isbuild = isbuild;
        this.leadid = leadid;
        this.reporttime = reporttime;
        this.starttime = starttime;
        this.endtime = endtime;
        this.source = source;
        this.creative = creative;
        this.advance = advance;
        this.period = period;
        this.alinvest = alinvest;
        this.preinvest = preinvest;
        this.alutility = alutility;
        this.preutility = preutility;
        this.alstyle = alstyle;
        this.prestyle = prestyle;
        this.outinvest = outinvest;
        this.newarts = newarts;
        this.newproduct = newproduct;
        this.newequip = newequip;
        this.soft = soft;
        this.paper = paper;
        this.standard = standard;
        this.other1 = other1;
        this.other2 = other2;
        this.advantage = advantage;
        this.harvest = harvest;
        this.ispdf = ispdf;
        this.goal = goal;
        this.base = base;
        this.purpose = purpose;
        this.content = content;
        this.stagegoal = stagegoal;
        this.techgoal = techgoal;
        this.bengoal = bengoal;
        this.workgoal = workgoal;
        this.preview = preview;
        this.environment = environment;
        this.othernote = othernote;
        this.fundnote = fundnote;
        this.templetpath = templetpath;
        this.wordpath = wordpath;
        this.pdfpath = pdfpath;
        this.reportpath = reportpath;
    }

   
    // Property accessors
    @Id
    
    @Column(name="id", unique=true, nullable=false, insertable=true, updatable=true)

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="serviceid", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getServiceid() {
        return this.serviceid;
    }
    
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }
    
    @Column(name="type", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    
    @Column(name="kind", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getKind() {
        return this.kind;
    }
    
    public void setKind(Integer kind) {
        this.kind = kind;
    }
    
    @Column(name="rank", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
    
    @Column(name="secret", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getSecret() {
        return this.secret;
    }
    
    public void setSecret(Integer secret) {
        this.secret = secret;
    }
    
    @Column(name="activity", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getActivity() {
        return this.activity;
    }
    
    public void setActivity(Integer activity) {
        this.activity = activity;
    }
    
    @Column(name="invoate", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getInvoate() {
        return this.invoate;
    }
    
    public void setInvoate(Integer invoate) {
        this.invoate = invoate;
    }
    
    @Column(name="region", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getRegion() {
        return this.region;
    }
    
    public void setRegion(Integer region) {
        this.region = region;
    }
    
    @Column(name="techregion", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getTechregion() {
        return this.techregion;
    }
    
    public void setTechregion(Integer techregion) {
        this.techregion = techregion;
    }
    
    @Column(name="year", unique=false, nullable=true, insertable=true, updatable=true, length=10)

    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    
    @Column(name="name", unique=false, nullable=true, insertable=true, updatable=true)

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="versionnum", unique=false, nullable=true, insertable=true, updatable=true, length=50)

    public String getVersionnum() {
        return this.versionnum;
    }
    
    public void setVersionnum(String versionnum) {
        this.versionnum = versionnum;
    }
    
    @Column(name="acceptnum", unique=false, nullable=true, insertable=true, updatable=true, length=50)

    public String getAcceptnum() {
        return this.acceptnum;
    }
    
    public void setAcceptnum(String acceptnum) {
        this.acceptnum = acceptnum;
    }
    
    @Column(name="projectnum", unique=false, nullable=true, insertable=true, updatable=true, length=50)

    public String getProjectnum() {
        return this.projectnum;
    }
    
    public void setProjectnum(String projectnum) {
        this.projectnum = projectnum;
    }
    
    @Column(name="filenum", unique=false, nullable=true, insertable=true, updatable=true, length=50)

    public String getFilenum() {
        return this.filenum;
    }
    
    public void setFilenum(String filenum) {
        this.filenum = filenum;
    }
    
    @Column(name="seq", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getSeq() {
        return this.seq;
    }
    
    public void setSeq(Integer seq) {
        this.seq = seq;
    }
    
    @Column(name="progessid", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getProgessid() {
        return this.progessid;
    }
    
    public void setProgessid(Integer progessid) {
        this.progessid = progessid;
    }
    
    @Column(name="isover", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getIsover() {
        return this.isover;
    }
    
    public void setIsover(Integer isover) {
        this.isover = isover;
    }
    
    @Column(name="isbuild", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getIsbuild() {
        return this.isbuild;
    }
    
    public void setIsbuild(Integer isbuild) {
        this.isbuild = isbuild;
    }
    
    @Column(name="leadid", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getLeadid() {
        return this.leadid;
    }
    
    public void setLeadid(Integer leadid) {
        this.leadid = leadid;
    }
@Temporal(TemporalType.DATE)
    @Column(name="reporttime", unique=false, nullable=true, insertable=true, updatable=true, length=10)

    public Date getReporttime() {
        return this.reporttime;
    }
    
    public void setReporttime(Date reporttime) {
        this.reporttime = reporttime;
    }
@Temporal(TemporalType.DATE)
    @Column(name="starttime", unique=false, nullable=true, insertable=true, updatable=true, length=10)

    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }
@Temporal(TemporalType.DATE)
    @Column(name="endtime", unique=false, nullable=true, insertable=true, updatable=true, length=10)

    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
    
    @Column(name="source", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getSource() {
        return this.source;
    }
    
    public void setSource(Integer source) {
        this.source = source;
    }
    
    @Column(name="creative", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getCreative() {
        return this.creative;
    }
    
    public void setCreative(Integer creative) {
        this.creative = creative;
    }
    
    @Column(name="advance", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getAdvance() {
        return this.advance;
    }
    
    public void setAdvance(Integer advance) {
        this.advance = advance;
    }
    
    @Column(name="period", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getPeriod() {
        return this.period;
    }
    
    public void setPeriod(Integer period) {
        this.period = period;
    }
    
    @Column(name="alinvest", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getAlinvest() {
        return this.alinvest;
    }
    
    public void setAlinvest(Integer alinvest) {
        this.alinvest = alinvest;
    }
    
    @Column(name="preinvest", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getPreinvest() {
        return this.preinvest;
    }
    
    public void setPreinvest(Integer preinvest) {
        this.preinvest = preinvest;
    }
    
    @Column(name="alutility", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getAlutility() {
        return this.alutility;
    }
    
    public void setAlutility(Integer alutility) {
        this.alutility = alutility;
    }
    
    @Column(name="preutility", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getPreutility() {
        return this.preutility;
    }
    
    public void setPreutility(Integer preutility) {
        this.preutility = preutility;
    }
    
    @Column(name="alstyle", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getAlstyle() {
        return this.alstyle;
    }
    
    public void setAlstyle(Integer alstyle) {
        this.alstyle = alstyle;
    }
    
    @Column(name="prestyle", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getPrestyle() {
        return this.prestyle;
    }
    
    public void setPrestyle(Integer prestyle) {
        this.prestyle = prestyle;
    }
    
    @Column(name="outinvest", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getOutinvest() {
        return this.outinvest;
    }
    
    public void setOutinvest(Integer outinvest) {
        this.outinvest = outinvest;
    }
    
    @Column(name="newarts", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getNewarts() {
        return this.newarts;
    }
    
    public void setNewarts(Integer newarts) {
        this.newarts = newarts;
    }
    
    @Column(name="newproduct", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getNewproduct() {
        return this.newproduct;
    }
    
    public void setNewproduct(Integer newproduct) {
        this.newproduct = newproduct;
    }
    
    @Column(name="newequip", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getNewequip() {
        return this.newequip;
    }
    
    public void setNewequip(Integer newequip) {
        this.newequip = newequip;
    }
    
    @Column(name="soft", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getSoft() {
        return this.soft;
    }
    
    public void setSoft(Integer soft) {
        this.soft = soft;
    }
    
    @Column(name="paper", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getPaper() {
        return this.paper;
    }
    
    public void setPaper(Integer paper) {
        this.paper = paper;
    }
    
    @Column(name="standard", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getStandard() {
        return this.standard;
    }
    
    public void setStandard(Integer standard) {
        this.standard = standard;
    }
    
    @Column(name="other1", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getOther1() {
        return this.other1;
    }
    
    public void setOther1(Integer other1) {
        this.other1 = other1;
    }
    
    @Column(name="other2", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getOther2() {
        return this.other2;
    }
    
    public void setOther2(Integer other2) {
        this.other2 = other2;
    }
    
    @Column(name="advantage", unique=false, nullable=true, insertable=true, updatable=true, length=30)

    public String getAdvantage() {
        return this.advantage;
    }
    
    public void setAdvantage(String advantage) {
        this.advantage = advantage;
    }
    
    @Column(name="harvest", unique=false, nullable=true, insertable=true, updatable=true, length=30)

    public String getHarvest() {
        return this.harvest;
    }
    
    public void setHarvest(String harvest) {
        this.harvest = harvest;
    }
    
    @Column(name="ispdf", unique=false, nullable=true, insertable=true, updatable=true)

    public Integer getIspdf() {
        return this.ispdf;
    }
    
    public void setIspdf(Integer ispdf) {
        this.ispdf = ispdf;
    }
    
    @Column(name="goal", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getGoal() {
        return this.goal;
    }
    
    public void setGoal(String goal) {
        this.goal = goal;
    }
    
    @Column(name="base", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getBase() {
        return this.base;
    }
    
    public void setBase(String base) {
        this.base = base;
    }
    
    @Column(name="purpose", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
    
    @Column(name="content", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    
    @Column(name="stagegoal", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getStagegoal() {
        return this.stagegoal;
    }
    
    public void setStagegoal(String stagegoal) {
        this.stagegoal = stagegoal;
    }
    
    @Column(name="techgoal", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getTechgoal() {
        return this.techgoal;
    }
    
    public void setTechgoal(String techgoal) {
        this.techgoal = techgoal;
    }
    
    @Column(name="bengoal", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getBengoal() {
        return this.bengoal;
    }
    
    public void setBengoal(String bengoal) {
        this.bengoal = bengoal;
    }
    
    @Column(name="workgoal", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getWorkgoal() {
        return this.workgoal;
    }
    
    public void setWorkgoal(String workgoal) {
        this.workgoal = workgoal;
    }
    
    @Column(name="preview", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getPreview() {
        return this.preview;
    }
    
    public void setPreview(String preview) {
        this.preview = preview;
    }
    
    @Column(name="environment", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getEnvironment() {
        return this.environment;
    }
    
    public void setEnvironment(String environment) {
        this.environment = environment;
    }
    
    @Column(name="othernote", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getOthernote() {
        return this.othernote;
    }
    
    public void setOthernote(String othernote) {
        this.othernote = othernote;
    }
    
    @Column(name="fundnote", unique=false, nullable=true, insertable=true, updatable=true, length=65535)

    public String getFundnote() {
        return this.fundnote;
    }
    
    public void setFundnote(String fundnote) {
        this.fundnote = fundnote;
    }
    
    @Column(name="templetpath", unique=false, nullable=true, insertable=true, updatable=true)

    public String getTempletpath() {
        return this.templetpath;
    }
    
    public void setTempletpath(String templetpath) {
        this.templetpath = templetpath;
    }
    
    @Column(name="wordpath", unique=false, nullable=true, insertable=true, updatable=true)

    public String getWordpath() {
        return this.wordpath;
    }
    
    public void setWordpath(String wordpath) {
        this.wordpath = wordpath;
    }
    
    @Column(name="pdfpath", unique=false, nullable=true, insertable=true, updatable=true)

    public String getPdfpath() {
        return this.pdfpath;
    }
    
    public void setPdfpath(String pdfpath) {
        this.pdfpath = pdfpath;
    }
    
    @Column(name="reportpath", unique=false, nullable=true, insertable=true, updatable=true)

    public String getReportpath() {
        return this.reportpath;
    }
    
    public void setReportpath(String reportpath) {
        this.reportpath = reportpath;
    }
   








}